#!/bin/bash
# piff_lomo_job.sh - cape LOMO ladder (supervisor decision 2026-07-13 under
# Sanaa's full-independence ruling; unblocked from the Monday held list).
# FIVE sequential leave-one-member-out folds of the UNCONDITIONED cape
# baseline config (isolates generalization of the KNOWN model; the conditioned
# model's LOMO comes after the conditioned ensemble verdict). One GPU job,
# ~8.5 h (5 x 100 ep x ~60 s). Fold conf files are generated by the submitter
# (conf_lomo_cape_<member>.yaml: conf_piff_cape.yaml + lomo_holdout).
#
# Usage: qsub -N pLomo_cape -q ibgpu.q -l gpu=1 -o <logs>/... -j y -cwd -V \
#             piff_lomo_job.sh

#$ -S /bin/bash
#$ -cwd
#$ -V

set -e

QG_ROOT=/gdata/projects/ml_scope/Closure_modeling/QG-closure
BRANCH="$QG_ROOT/qg-sgs-closure"

source "$QG_ROOT/qg-env-piff/bin/activate"
export TMPDIR="$QG_ROOT/tmp"
export MPLCONFIGDIR="$QG_ROOT/mplcache"
export PYTHONUNBUFFERED=1

mkdir -p "$QG_ROOT/cache/torch" "$QG_ROOT/cache/triton" "$QG_ROOT/cache/nvrtc"
export TORCH_EXTENSIONS_DIR="$QG_ROOT/cache/torch"
export TRITON_CACHE_DIR="$QG_ROOT/cache/triton"
export PYTORCH_KERNEL_CACHE_PATH="$QG_ROOT/cache/nvrtc"

if command -v nvidia-smi >/dev/null 2>&1; then
    IDLE_GPU=$(nvidia-smi --query-gpu=index,memory.used --format=csv,noheader,nounits \
        | sort -t',' -k2 -n | head -1 | awk -F',' '{gsub(/ /,""); print $1}')
    export CUDA_VISIBLE_DEVICES="$IDLE_GPU"
    echo "[piff_lomo] selected GPU $IDLE_GPU on $HOSTNAME"
fi

cd "$BRANCH/ml_closure"
for m in const sine ramp ou tel; do
    CONF="conf_lomo_cape_$m.yaml"
    RN="cape_lomo_$m"
    if [ -e "runs_piff/$RN/best.pt" ]; then
        echo "[piff_lomo] $RN exists — skipping (resume-safe)"
        continue
    fi
    echo "[piff_lomo] ===== fold $m ($(date -u +%FT%TZ)) ====="
    python -u train_piff.py --config "$CONF" --run-name "$RN"
    python -u eval_piff.py --ckpt "runs_piff/$RN/best.pt" --config "$CONF"
done
echo "[piff_lomo] all folds done at $(date -u +%FT%TZ)"
