"""
rollout_multistep_comparison.py
================================

Multi-step rollout comparison of three trajectories starting from the same IC:

    (i)  fine reference (truth):   M * K AB2CN2 steps of size h_fine = Delta_T / K
    (ii) coarse no closure:        M     AB2CN2 steps of size Delta_T
    (iii)coarse with closure:      M     AB2CN2 steps of size Delta_T,
                                   each augmented by e_anal + e_NN_pred

Why this figure exists
----------------------
At validated (Delta_T, K) = (1e-3, 100), the per-step truncation error is
~ Delta_T^3 * |E| ~ 1e-9 -- invisible against |omega| ~ O(1) on any
field-space colorbar. The closure's job is to extend usable Delta_T much
higher than the bare scheme allows.  Error accumulation over M coarse
steps is what makes the closure benefit visible:

    bare:    error ~ M * C * Delta_T^3
    closure: error ~ M * C * Delta_T^3 * eps_NN     (eps_NN ~ 0.19)

so over an extended horizon T_rollout = M * Delta_T the closure trajectory
stays close to truth while the bare-coarse one drifts.

This script also fixes the broken spectra in visualize_rollout_correction.py:
the previous version *averaged* |omega_hat|^2 within each k-annulus, which
divides out the k-density-of-states factor and flattens the canonical
k^{-3} forward-enstrophy-cascade slope.  Here we sum within each annulus,
divide by bin width dk, and use physical wavenumbers (correct for any
L_x, L_y, not just 2*pi).

Outputs
-------
<out-dir>/rollout_multistep_<ic_tag>.png         four-row figure
<out-dir>/rollout_multistep_<ic_tag>.npz         all rollout arrays
<out-dir>/rollout_multistep_<ic_tag>.json        run metadata

Usage
-----
  python rollout_multistep_comparison.py \
      --run-dir  <training_run_dir> \
      --root-dir <dataset_root_dir> \
      --n-steps  500 \
      --ic-index 100 \
      --split    val \
      --out-dir  <run-dir>
"""

from __future__ import annotations
import argparse
import json
import sys
import time
from pathlib import Path
from typing import Optional

import numpy as np
import torch
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

# Locate the training directory (which contains dataset.py + model_fixD.py)
# by walking up from this script's location.  This script may live in
# training/plotting/trainvD/ or directly in training/; either way, find the
# nearest ancestor that contains dataset.py and put it first on sys.path.
def _find_training_dir():
    here = Path(__file__).resolve().parent
    for ancestor in [here, *here.parents]:
        if (ancestor / 'dataset.py').exists():
            return ancestor
    return here  # fallback; import will fail loudly downstream
_training_dir = _find_training_dir()
sys.path.insert(0, str(_training_dir))
sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path('.').resolve()))
print(f"[rollout] training dir on sys.path: {_training_dir}")


# --------------------------------------------------------------------------- #
# Solver primitives (lifted from build_training_data_fixD.py to keep this     #
# script self-contained -- exact same operator definitions).                  #
# --------------------------------------------------------------------------- #

def J_phys(psi_phys, omega_phys, derivative):
    """Jacobian J(psi, omega) in physical space via spectral derivatives.

    2/3 dealiasing IS applied: after to_spectral(u*q) and to_spectral(v*q)
    we zero the modes above k_cut = (2/3)*k_nyquist via derivative.alias_mask.
    Without this, modes k1 + k2 > k_nyquist generated by the physical-space
    product fold back into the resolved spectrum (aliasing), and over O(10^6)
    timesteps this fills the high-k tail with broadband noise and drives a
    spurious cascade-like enstrophy growth. The production solver applies
    dealiasing at the assembled-RHS level via derivative.dealias() in
    qg.solver.opt._init_operator.Operator.RHS; we apply it inside the
    Jacobian instead, which is mathematically equivalent (the only non-linear
    operation in the QG RHS is this Jacobian).
    """
    from qg.solver.opt.basis import to_spectral, to_physical
    psih = to_spectral(psi_phys)
    qh   = to_spectral(omega_phys)
    uh = -1 * derivative.dy * psih
    vh = +1 * derivative.dx * psih
    u = to_physical(uh)
    v = to_physical(vh)
    q = to_physical(qh)
    uq_h = to_spectral(u * q)
    vq_h = to_spectral(v * q)
    # Apply 2/3 dealiasing to the nonlinear products before computing the
    # Jacobian.  We clone first because derivative.dealias() is in-place.
    uq_h = uq_h.clone()
    vq_h = vq_h.clone()
    derivative.dealias(uq_h)
    derivative.dealias(vq_h)
    j_hat = derivative.dx * uq_h + derivative.dy * vq_h
    return to_physical(j_hat)


def L_op(omega_phys, L_hat):
    from qg.solver.opt.basis import to_spectral, to_physical
    return to_physical(L_hat * to_spectral(omega_phys))


def build_L_hat(derivative, nu, mu, beta):
    L_hat = nu * derivative.laplacian - mu
    if beta != 0.0:
        L_hat = L_hat - beta * derivative.dx * derivative.inv_laplacian
    return L_hat


def ab2cn2_step_spectral(qh_n, qh_nm1, dt, derivative, L_hat, F_phys):
    """One AB2CN2 IMEX step -- byte-identical to build_training_data_fixD.py."""
    from qg.solver.opt.basis import to_spectral, to_physical

    def N_at_qh(qh):
        psi_hat = derivative.inv_laplacian * qh
        psi = to_physical(psi_hat)
        omega = to_physical(qh)
        N_phys = -1.0 * J_phys(psi, omega, derivative)
        if F_phys is not None:
            N_phys = N_phys + F_phys
        return to_spectral(N_phys)

    Nh_n   = N_at_qh(qh_n)
    Nh_nm1 = N_at_qh(qh_nm1)
    AB2_Nh = 1.5 * Nh_n - 0.5 * Nh_nm1
    rhs_hat   = qh_n + dt * (0.5 * L_hat * qh_n + AB2_Nh)
    denom_hat = 1.0 - 0.5 * dt * L_hat
    return rhs_hat / denom_hat


def rk4_step(omega, dt, derivative, L_hat, F_phys):
    def rhs(om):
        from qg.solver.opt.basis import to_spectral, to_physical
        psi_hat = derivative.inv_laplacian * to_spectral(om)
        psi = to_physical(psi_hat)
        N = -1.0 * J_phys(psi, om, derivative)
        if F_phys is not None:
            N = N + F_phys
        return L_op(om, L_hat) + N
    k1 = rhs(omega)
    k2 = rhs(omega + 0.5 * dt * k1)
    k3 = rhs(omega + 0.5 * dt * k2)
    k4 = rhs(omega + dt * k3)
    return omega + (dt / 6.0) * (k1 + 2 * k2 + 2 * k3 + k4)


# --------------------------------------------------------------------------- #
# E_anal: (1/12)[L^3 omega + L^2 N] -- needed at every coarse step            #
# --------------------------------------------------------------------------- #

def E_analytical_phys(omega_phys, derivative, L_hat, F_phys):
    """Analytical part of the closure bracket: (1/12) * [L^3 omega + L^2 N]."""
    from qg.solver.opt.basis import to_spectral, to_physical
    qh = to_spectral(omega_phys)
    L3_omega = to_physical(L_hat ** 3 * qh)

    psi_hat = derivative.inv_laplacian * qh
    psi = to_physical(psi_hat)
    N = -1.0 * J_phys(psi, omega_phys, derivative)
    if F_phys is not None:
        N = N + F_phys
    Nh = to_spectral(N)
    L2_N = to_physical(L_hat ** 2 * Nh)
    return (1.0 / 12.0) * (L3_omega + L2_N)


# --------------------------------------------------------------------------- #
# Spectra -- CORRECTED radial sum (not radial mean)                           #
# --------------------------------------------------------------------------- #

def radial_sum_spectrum(field2d, Lx, Ly):
    """
    Return (k_centers, P(k)) where
        P(k) dk = sum over k-shell of |f_hat(k)|^2

    Uses physical wavenumbers (kx = 2*pi*n/Lx), and *sums* within each annulus.
    Bin width dk is chosen as the larger of (2*pi/Lx, 2*pi/Ly) so each bin
    contains at least one grid mode.

    The previous visualization used:
        - integer-index kx (only correct for L = 2*pi)
        - mean within annulus (divides out the k-density-of-states factor)
      which is why the previous E(k), Z(k) plots looked flat instead of
      showing the canonical k^{-3} forward-enstrophy-cascade slope.
    """
    Ny, Nx = field2d.shape
    # Physical wavenumbers
    kx = np.fft.fftfreq(Nx, d=Lx / Nx) * 2.0 * np.pi   # shape (Nx,)
    ky = np.fft.fftfreq(Ny, d=Ly / Ny) * 2.0 * np.pi
    KX, KY = np.meshgrid(kx, ky, indexing='xy')
    Kmag = np.sqrt(KX ** 2 + KY ** 2)
    # Unitary FFT normalization: Parseval gives sum |f_hat|^2 / (Nx*Ny) = mean |f|^2
    fhat = np.fft.fft2(field2d) / (Nx * Ny)
    psd  = np.abs(fhat) ** 2

    dk = max(2.0 * np.pi / Lx, 2.0 * np.pi / Ly)
    kmax = float(Kmag.max())
    bins = np.arange(0.0, kmax + dk, dk)
    sp, _ = np.histogram(Kmag.ravel(), bins=bins, weights=psd.ravel())  # SUM
    kc = 0.5 * (bins[:-1] + bins[1:])
    # P(k) so that sum P(k) * dk = total variance:
    return kc, sp / dk


def enstrophy_spectrum(omega_phys, Lx, Ly):
    """Z(k) = 0.5 * sum_{|k|=k} |omega_hat(k)|^2 / dk."""
    kc, sp = radial_sum_spectrum(omega_phys, Lx, Ly)
    return kc, 0.5 * sp


def energy_spectrum(omega_phys, Lx, Ly):
    """E(k) = 0.5 * k^{-2} * sum_{|k|=k} |omega_hat(k)|^2 / dk.

    Uses omega = -lap psi  =>  |omega_hat|^2 = k^4 |psi_hat|^2,
    so KE density 0.5 |u_hat|^2 = 0.5 k^2 |psi_hat|^2 = 0.5 k^{-2}|omega_hat|^2.
    """
    kc, sp = radial_sum_spectrum(omega_phys, Lx, Ly)
    k_safe = np.where(kc <= 0, np.inf, kc)
    return kc, 0.5 * sp / (k_safe ** 2)


# --------------------------------------------------------------------------- #
# Model loading + input-stack assembly at inference time                      #
# --------------------------------------------------------------------------- #

def load_model(run_dir, n_in, hidden, kernel, base_channels, depth, model_name,
               device='cpu'):
    if model_name in ('bilinear_closure', 'bilin', 'fixd_v2'):
        from model_fixD import build_model
        model = build_model(model_name, in_channels=n_in,
                            hidden=hidden, kernel=kernel)
    else:
        from model import build_model
        if model_name == 'unet':
            model = build_model('unet', in_channels=n_in,
                                base_channels=base_channels, kernel=kernel)
        else:
            model = build_model('cnn', in_channels=n_in,
                                hidden_channels=hidden, depth=depth,
                                kernel=kernel)
    ckpt_path = run_dir / 'model_best.pt'
    if not ckpt_path.exists():
        ckpt_path = run_dir / 'model_last.pt'
    if not ckpt_path.exists():
        raise FileNotFoundError(f"no model_best.pt or model_last.pt in {run_dir}")
    state = torch.load(ckpt_path, map_location=device, weights_only=False)
    if 'model_state' in state:
        model.load_state_dict(state['model_state'])
    elif 'state_dict' in state:
        model.load_state_dict(state['state_dict'])
    else:
        model.load_state_dict(state)
    model.to(device).eval()
    print(f"  loaded checkpoint: {ckpt_path}")
    return model


def assemble_inputs(input_fields, omega_stack, psi_stack, derivative,
                    L_hat, F_phys, dtype, device):
    """Build the C_in-channel input tensor (1, C, Ny, Nx) from the current
    rollout state.

    omega_stack: list-of-tensors [omega_0, omega_m1, omega_m2, ...]
                 (most recent first).  Each (1, Ny, Nx) torch tensor.
    psi_stack:   matching list of psi_phys tensors.

    Only the input fields actually used by the loaded model are computed.
    The bilinear v2 net uses just the 6 channels:
        omega_0 omega_m1 omega_m2 psi_0 psi_m1 psi_m2
    so the heavy analytical ones (L^k omega, N_0, ...) are only built on demand.
    """
    from qg.solver.opt.basis import to_spectral, to_physical
    chans = []

    # Trivial channel: pulls from one of the stacks. Adds zero-pad if needed.
    def grab_omega(k):
        if k < len(omega_stack):
            return omega_stack[k]
        return torch.zeros_like(omega_stack[0])

    def grab_psi(k):
        if k < len(psi_stack):
            return psi_stack[k]
        return torch.zeros_like(psi_stack[0])

    def grad_psi_sq_phys():
        psih = to_spectral(psi_stack[0])
        u = to_physical(-1 * derivative.dy * psih)
        v = to_physical(+1 * derivative.dx * psih)
        return u * u + v * v

    def omega_grad(axis):
        qh = to_spectral(omega_stack[0])
        return to_physical((derivative.dx if axis == 'x' else derivative.dy) * qh)

    def N_now():
        N = -1.0 * J_phys(psi_stack[0], omega_stack[0], derivative)
        if F_phys is not None:
            N = N + F_phys
        return N

    def L_omega_phys(power):
        qh = to_spectral(omega_stack[0])
        return to_physical((L_hat ** power) * qh)

    def L_N_phys(power):
        Nh = to_spectral(N_now())
        return to_physical((L_hat ** power) * Nh)

    builders = {
        'omega_0':      lambda: grab_omega(0),
        'omega_m1':     lambda: grab_omega(1),
        'omega_m2':     lambda: grab_omega(2),
        'psi_0':        lambda: grab_psi(0),
        'psi_m1':       lambda: grab_psi(1),
        'psi_m2':       lambda: grab_psi(2),
        'grad_psi_sq':  grad_psi_sq_phys,
        'omega_x':      lambda: omega_grad('x'),
        'omega_y':      lambda: omega_grad('y'),
        'N_0':          N_now,
        'L_omega':      lambda: L_omega_phys(1),
        'L2_omega':     lambda: L_omega_phys(2),
        'L3_omega':     lambda: L_omega_phys(3),
        'L_N':          lambda: L_N_phys(1),
        'L2_N':         lambda: L_N_phys(2),
    }
    for field in input_fields:
        if field not in builders:
            raise ValueError(f"input field '{field}' not supported in rollout "
                             f"(if you need it, add a builder).")
        chans.append(builders[field]())
    # shape each (1, Ny, Nx) -> (1, C, Ny, Nx)
    x = torch.stack([c[0] for c in chans], dim=0)[None]
    return x.to(device=device, dtype=dtype)


# --------------------------------------------------------------------------- #
# Compute psi from omega (used for the psi stack)                             #
# --------------------------------------------------------------------------- #

def psi_from_omega(omega_phys, derivative):
    from qg.solver.opt.basis import to_spectral, to_physical
    psi_hat = derivative.inv_laplacian * to_spectral(omega_phys)
    return to_physical(psi_hat)


# --------------------------------------------------------------------------- #
# Diagnostics (per-step scalars)                                              #
# --------------------------------------------------------------------------- #

def diagnostics(omega_np):
    """RMS, total enstrophy, total energy (placeholders; energy needs psi).
    For this script we use simpler L2 norm + enstrophy from omega only."""
    Z = 0.5 * float(np.mean(omega_np ** 2))     # mean enstrophy
    rms = float(np.sqrt(np.mean(omega_np ** 2)))
    return rms, Z


# --------------------------------------------------------------------------- #
# The rollout loop                                                            #
# --------------------------------------------------------------------------- #
# (The actual rollout logic lives in `rollout_keep_all` inside `main()`, so it
# can close over args, model, etc., while keeping outputs / state local.)


# --------------------------------------------------------------------------- #
# Main                                                                        #
# --------------------------------------------------------------------------- #

def main():
    p = argparse.ArgumentParser(
        description="Multi-step rollout comparison (truth / bare coarse / "
                    "coarse + closure) and corrected spectra.")
    p.add_argument('--run-dir',  type=Path, required=True,
                   help='training run dir (config.json, model_best.pt)')
    p.add_argument('--root-dir', type=Path, required=True,
                   help='dataset root (manifest.json + samples/)')
    p.add_argument('--n-steps',  type=int, default=500,
                   help='number of COARSE steps to roll out (default 500)')
    p.add_argument('--snapshot-fracs', type=str, default='0,0.25,0.5,1.0',
                   help='comma-sep fractions of n_steps at which to render '
                        'omega panels (e.g. "0,0.25,0.5,1.0")')
    p.add_argument('--ic-index', type=int, default=0,
                   help='dataset index (within --split) of starting IC')
    p.add_argument('--split', type=str, default='val',
                   choices=['train', 'val', 'test'])
    p.add_argument('--device', type=str, default='cuda',
                   help='cuda | cpu (default cuda; falls back to cpu)')
    # No --dtype flag: state is hard-set to float64.  The closure makes
    # corrections at coef ~ Delta_T^3 = 1e-9 magnitude, which float32 cannot
    # represent; the model itself can stay float32, but the state arithmetic
    # must be float64.  See build_training_data_fixD_v2.py for the matching
    # convention on the training side.
    p.add_argument('--out-dir', type=Path, default=None)
    p.add_argument('--ic-tag', type=str, default=None,
                   help='filename tag; default uses ic_index')
    p.add_argument('--Delta-T-override', type=float, default=None,
                   help='If set, run the rollout at this Delta_T instead of '
                        'the one in the manifest.  The trained NN target is '
                        'Delta_T-INDEPENDENT (just the bracket L*Ndot - 5*Nddot), '
                        'so the same checkpoint can be deployed at any Delta_T '
                        'within the closure formulas regime of validity.  When '
                        'this is set, the input buffer is also resampled to '
                        'the new Delta_T spacing via ultrafine RK4 backward '
                        'from omega_0 so the FD stencils inside the NN see '
                        'uniformly-spaced states.  Useful for showing the '
                        'closure where it matters: at the deployment Delta_T '
                        'far from where bare-coarse is already near-exact.')
    p.add_argument('--K-override', type=int, default=None,
                   help='Override K (fine-steps-per-coarse).  If unset, kept '
                        'consistent with --Delta-T-override by holding h_fine '
                        'fixed.  If both --Delta-T-override and --K-override '
                        'are given, h_fine = Delta_T / K is recomputed.')
    args = p.parse_args()

    device = args.device if (args.device == 'cpu' or torch.cuda.is_available()) \
                          else 'cpu'
    dtype  = torch.float64
    out_dir = args.out_dir or args.run_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    ic_tag = args.ic_tag or f"ic{args.ic_index:04d}"
    print(f"[rollout] device={device}  state dtype=float64")
    print(f"[rollout] run_dir={args.run_dir}")
    print(f"[rollout] root_dir={args.root_dir}")
    print(f"[rollout] out_dir={out_dir}")

    # ----- Manifest ----- #
    with open(args.root_dir / 'manifest.json') as f:
        manifest = json.load(f)
    Nx, Ny = int(manifest['Nx']), int(manifest['Ny'])
    Lx, Ly = float(manifest['Lx']), float(manifest['Ly'])
    nu     = float(manifest['nu'])
    mu     = float(manifest.get('mu', 0.0))
    beta   = float(manifest.get('beta', 0.0))
    Delta_T = float(manifest['Delta_T'])
    K       = int(manifest.get('K', 100))
    h_fine  = float(manifest.get('h_fine', Delta_T / K))
    training_Delta_T = Delta_T   # remember the training value before overrides
    training_K       = K
    training_h_fine  = h_fine
    if args.Delta_T_override is not None or args.K_override is not None:
        if args.Delta_T_override is not None:
            Delta_T = float(args.Delta_T_override)
        if args.K_override is not None:
            K = int(args.K_override)
            h_fine = Delta_T / K
        else:
            # Keep h_fine fixed (matches what the solver would do if you
            # asked for the same fine resolution at a larger coarse step):
            #   K_new = round(Delta_T_new / h_fine_old)
            K = int(round(Delta_T / h_fine))
            h_fine = Delta_T / K   # exact ratio
        print(f"[rollout] OVERRIDE:  training Delta_T={training_Delta_T}, K={training_K}, h_fine={training_h_fine}")
        print(f"[rollout]            rollout  Delta_T={Delta_T}, K={K}, h_fine={h_fine}")
        if abs(Delta_T - training_Delta_T) > 1e-12:
            print(f"[rollout]  -- input buffer will be RESAMPLED to {Delta_T:.3e} "
                  f"spacing via ultrafine RK4 backward from omega_0.")
    print(f"[rollout] manifest: Nx={Nx} Ny={Ny} Lx={Lx:.4f} Ly={Ly:.4f}")
    print(f"[rollout]           nu={nu} mu={mu} beta={beta}")
    print(f"[rollout]           Delta_T={Delta_T} K={K} h_fine={h_fine}")

    # ----- Training config (input fields, model variant) ----- #
    cfg = json.loads((args.run_dir / 'config.json').read_text())
    input_fields = tuple(cfg.get('input_fields',
                                 ['omega_0', 'omega_m1', 'omega_m2',
                                  'psi_0',   'psi_m1',   'psi_m2']))
    target_field = cfg.get('target_field', 'f_NN_target')
    model_name   = cfg.get('model', 'bilinear_closure')
    normalize    = cfg.get('normalize', True)
    print(f"[rollout] inputs: {input_fields}")
    print(f"[rollout] target: {target_field}    model: {model_name}    "
          f"normalize={normalize}")

    # ----- Build the QG grid + operators ----- #
    from qg.solver.grid.cartesian import CartesianGrid
    from qg.solver.opt.derivative import Derivative
    # Operators MUST be float64.  The training-data builder uses precision='float64'
    # by default (build_training_data_fixD_v2.py line 801, args.dtype default 'float64'),
    # so the "truth" baked into the npz was produced by float64 operators.  The
    # rollout's bare/closure trajectories must use the same operator precision
    # so their bare-vs-truth comparison is apples-to-apples.  Beyond that, the
    # closure makes corrections at coef ~ Delta_T^3 = 1e-9 magnitude, which is
    # below float32's ~1e-7 relative precision -- float32 operators would bury
    # the entire closure signal in roundoff (as we observed empirically).
    # Hard-set, not conditional.
    grid = CartesianGrid(Nx=Nx, Ny=Ny, Lx=Lx, Ly=Ly, device=device,
                          precision='float64')
    derivative = Derivative(grid)
    for attr in ('dx', 'dy', 'laplacian', 'inv_laplacian'):
        setattr(derivative, attr, getattr(derivative, attr).to(device))
    L_hat = build_L_hat(derivative, nu=nu, mu=mu, beta=beta).to(device)
    F_phys = None  # no forcing for decaying turbulence
    # Sanity print on operator dtype
    print(f"[rollout] grid precision: float64   "
          f"L_hat dtype: {L_hat.dtype}   "
          f"derivative.dx dtype: {derivative.dx.dtype}")

    # ----- Dataset (for normalization stats + split indices) ----- #
    from dataset import ClosureDataset
    ds = ClosureDataset(root_dir=args.root_dir, split=args.split,
                         input_fields=input_fields,
                         target_field=target_field, normalize=normalize)
    # Normalization stats:
    #   - target_mean / target_std: scalar floats (one for the target channel)
    #   - input_mean  / input_std : per-channel tensors of shape (C,)
    # All four are None if normalize=False.
    if normalize:
        assert ds.target_mean is not None and ds.target_std is not None, \
            f"normalize=True but dataset returned target_mean/std=None"
        assert ds.input_mean is not None and ds.input_std is not None, \
            f"normalize=True but dataset returned input_mean/std=None"
        target_mean = torch.as_tensor(ds.target_mean, dtype=dtype, device=device)
        target_std  = torch.as_tensor(ds.target_std,  dtype=dtype, device=device)
        # input_mean / input_std are 1D tensors of length C_in. We broadcast
        # them against (B, C, Ny, Nx) by reshaping to (1, C, 1, 1).
        input_mean = ds.input_mean.to(dtype=dtype, device=device).reshape(1, -1, 1, 1)
        input_std  = ds.input_std .to(dtype=dtype, device=device).reshape(1, -1, 1, 1)
        print(f"[rollout] target normalization: mean={float(target_mean):.4e}  "
              f"std={float(target_std):.4e}")
        in_mean_list = [float(v) for v in ds.input_mean]
        in_std_list  = [float(v) for v in ds.input_std]
        for fld, m, s in zip(input_fields, in_mean_list, in_std_list):
            print(f"           input '{fld:>10s}': mean={m:+.4e}  std={s:.4e}")
    else:
        target_mean = target_std = input_mean = input_std = None
        print(f"[rollout] target/input normalization: NONE")

    def normalize_inputs(x):
        """Apply per-channel input normalization to x: (B, C, Ny, Nx)."""
        if normalize:
            return (x - input_mean) / input_std
        return x

    def denormalize_target(yhat):
        """Map model output to raw f_NN_target.  yhat shape: (B, 1, Ny, Nx).
        If normalize=True: y_raw = yhat * target_std + target_mean.
        If normalize=False: y_raw = yhat (already raw).
        """
        if normalize:
            return yhat * target_std + target_mean
        return yhat

    # ----- Load NN ----- #
    model = load_model(args.run_dir, n_in=len(input_fields),
                       hidden=cfg.get('hidden_channels', 64),
                       kernel=cfg.get('kernel', 3),
                       base_channels=cfg.get('base_channels', 32),
                       depth=cfg.get('depth', 6),
                       model_name=model_name, device=device)

    # The model was trained in float32 (its parameters are float32 on disk).
    # The solver state is float64 because  coef = Delta_T^3 (1 - 1/K^2) ~ 1e-9
    # and  om_bare + coef * f_NN_pred  loses ~9 digits of precision when done
    # in float32.  So: keep state buffers / increments in float64, downcast
    # ONLY at the NN boundary (input -> model_dtype, output -> back to float64
    # before scaling).  Upcasting the model parameters to float64 would not
    # add accuracy -- the trained weights are float32 by construction.
    model_dtype = next(model.parameters()).dtype
    print(f"[rollout] model parameter dtype: {model_dtype}   "
          f"(solver state dtype: {dtype})")

    # ----- Load the IC stack from one sample ----- #
    split_indices = ds.indices
    manifest_idx = int(split_indices[args.ic_index])
    npz_path = args.root_dir / 'samples' / f'sample_{manifest_idx:06d}.npz'
    print(f"[rollout] IC: split index {args.ic_index}  -> manifest #{manifest_idx}")
    print(f"[rollout]     {npz_path}")
    rec = np.load(npz_path)
    print(f"[rollout] sample keys: {sorted(rec.files)}")

    def load_field(name):
        if name not in rec.files:
            raise KeyError(
                f"sample npz missing required field '{name}'. "
                f"Available: {sorted(rec.files)}. "
                f"You probably need to rebuild the dataset with "
                f"build_training_data_fixD_v2.py, which saves "
                f"omega_m2, psi_m1, psi_m2.")
        a = rec[name].astype(np.float64)
        if a.ndim == 3: a = a[0]
        return torch.tensor(a, dtype=dtype, device=device)[None]

    # Read all 6 v2 fields directly. The v2 builder saves three coarse-spaced
    # states (each produced by ultrafine RK4 forward from the seed), so
    # nothing needs to be recomputed:
    #   omega_0  = seed + 3*Delta_T,  psi_0  = inv_lap(omega_0)
    #   omega_m1 = seed + 2*Delta_T,  psi_m1 = inv_lap(omega_m1)
    #   omega_m2 = seed + 1*Delta_T,  psi_m2 = inv_lap(omega_m2)
    omega_0_t  = load_field('omega_0')
    omega_m1_t = load_field('omega_m1')
    omega_m2_t = load_field('omega_m2')
    psi_0_t    = load_field('psi_0')
    psi_m1_t   = load_field('psi_m1')
    psi_m2_t   = load_field('psi_m2')

    # Scalar metadata: when is this sample, physically?
    # build_training_data_fixD_v2 saves seed_t (and seed_idx, batch_idx) into
    # every sample npz, and omega_0 sits at seed_t + 3*Delta_T_training by
    # construction.  These tell us exactly where in the parent FR trajectory
    # we are.  Critical for sanity-checking the spectrum: if seed_t ~ 30 we
    # are deep in developed-decay regime and a broad spectrum is expected;
    # if seed_t ~ 0 the IC is band-limited and should look like the YAML.
    seed_t_from_npz   = float(rec['seed_t'])   if 'seed_t'   in rec.files else float('nan')
    seed_idx_from_npz = int(rec['seed_idx'])   if 'seed_idx' in rec.files else -1
    batch_idx_npz     = int(rec['batch_idx'])  if 'batch_idx' in rec.files else -1
    t_omega0_abs = seed_t_from_npz + 3 * training_Delta_T
    print(f"[rollout] sample metadata from npz:")
    print(f"           seed_t   = {seed_t_from_npz:.6f}   "
          f"(parent FR snapshot index {seed_idx_from_npz}, batch {batch_idx_npz})")
    print(f"           omega_0 sits at t = seed_t + 3*DT_train = "
          f"{t_omega0_abs:.6f}  (DT_train = {training_Delta_T:g})")

    omega_init_stack = [omega_0_t, omega_m1_t, omega_m2_t]
    psi_init_stack   = [psi_0_t,   psi_m1_t,   psi_m2_t]
    print(f"[rollout] IC stack (read from npz, no recomputation):")
    print(f"           |omega_0| ={float(torch.sqrt((omega_0_t**2).mean())):.4e}  "
          f"|omega_m1|={float(torch.sqrt((omega_m1_t**2).mean())):.4e}  "
          f"|omega_m2|={float(torch.sqrt((omega_m2_t**2).mean())):.4e}")

    # If we are running at a different Delta_T than the training one, the
    # bilinear NN's input FD-stencils want omega_{m1,m2} at the NEW Delta_T
    # spacing relative to omega_0.  Resample by FORWARD ultrafine RK4 from the
    # npz's omega_0:
    #     t = 0                  -> seed (= npz omega_0)
    #     t = +1*Delta_T_rollout -> save as new omega_m1
    #     t = +2*Delta_T_rollout -> save as new omega_0  (the new IC for rollout)
    #
    # And the new omega_m2 is the npz's omega_0 itself (the seed sits at -Delta_T
    # relative to the new omega_m1, i.e. -2*Delta_T relative to the new omega_0).
    #
    # Wait -- AB2 needs 3 states at Delta_T spacing.  Cleaner: go forward by
    # 3*Delta_T_rollout, snapshot at +Delta_T, +2*Delta_T, +3*Delta_T:
    #     +1*Delta_T_rollout  -> new omega_m2
    #     +2*Delta_T_rollout  -> new omega_m1
    #     +3*Delta_T_rollout  -> new omega_0
    # exactly mirroring what the builder does to construct training samples.
    # All forward in time => well-posed even on the viscous PDE.
    #
    # Cost: 3*Delta_T_rollout / h_ultrafine ultrafine RK4 steps.  At
    # Delta_T_rollout=1e-2, h_ultrafine=1e-6 (from training manifest), that's
    # 30000 RK4 steps.  On GPU, ~30s; on CPU, ~minutes but only once at startup.
    if args.Delta_T_override is not None and abs(Delta_T - training_Delta_T) > 1e-12:
        h_ultrafine = float(manifest.get('h_ultrafine', training_h_fine / 10.0))
        n_uf_per_dT = int(round(Delta_T / h_ultrafine))
        # Use the same h_ultrafine the builder used, so this matches the
        # builder's stencil construction exactly (modulo IC differences).
        print(f"[rollout] FORWARD-resampling buffer to Delta_T={Delta_T:.3e} via "
              f"{3*n_uf_per_dT} ultrafine RK4 steps of size +{h_ultrafine:.3e}")
        print(f"           (mirror of build_training_data_fixD_v2.py's stencil "
              f"warmup, forward in time => well-posed)")
        # Sanity check: nu * k_max^2 * (3*Delta_T) should give the high-k
        # *damping* over the forward walk.  Just print for transparency.
        k_max = float(min(Nx, Ny) // 3)
        damp_at_kmax_3dT = float(np.exp(-nu * k_max**2 * 3 * Delta_T))
        print(f"           high-k damping at k_max~{k_max:.0f} over 3*Delta_T: "
              f"{damp_at_kmax_3dT:.3e}x (anything <1 is good; backward would be 1/that)")
        seed = omega_0_t.clone()
        omega_cur = seed
        omega_m2_new = None
        omega_m1_new = None
        omega_0_new  = None
        for step in range(3 * n_uf_per_dT):
            omega_cur = rk4_step(omega_cur, +h_ultrafine, derivative, L_hat, F_phys)
            if step + 1 == 1 * n_uf_per_dT:
                omega_m2_new = omega_cur.clone()
            elif step + 1 == 2 * n_uf_per_dT:
                omega_m1_new = omega_cur.clone()
            elif step + 1 == 3 * n_uf_per_dT:
                omega_0_new  = omega_cur.clone()
        omega_0_t  = omega_0_new.detach()
        omega_m1_t = omega_m1_new.detach()
        omega_m2_t = omega_m2_new.detach()
        psi_0_t    = psi_from_omega(omega_0_t,  derivative)
        psi_m1_t   = psi_from_omega(omega_m1_t, derivative)
        psi_m2_t   = psi_from_omega(omega_m2_t, derivative)
        omega_init_stack = [omega_0_t, omega_m1_t, omega_m2_t]
        psi_init_stack   = [psi_0_t,   psi_m1_t,   psi_m2_t]
        # Mark that we forward-walked; downstream closure diagnostic block
        # should NOT compare to npz-saved f_NN_target / e_total (those were
        # computed for the npz's original omega_0, not the new one).
        forward_resampled = True
        print(f"[rollout] new IC: |omega_0|={float(torch.sqrt((omega_0_t**2).mean())):.4e}  "
              f"|omega_m1|={float(torch.sqrt((omega_m1_t**2).mean())):.4e}  "
              f"|omega_m2|={float(torch.sqrt((omega_m2_t**2).mean())):.4e}")
        print(f"[rollout] note: new omega_0 sits at t = seed_t_npz + 3*Delta_T_rollout "
              f"= {3*Delta_T:.4f} *past* the npz's omega_0;")
        print(f"           NPZ-based closure diagnostic predictions will be skipped "
              f"(npz f_NN_target was for the OLD omega_0).")
    else:
        forward_resampled = False

    print(f"           |psi_0|   ={float(torch.sqrt((psi_0_t**2).mean())):.4e}  "
          f"|psi_m1|  ={float(torch.sqrt((psi_m1_t**2).mean())):.4e}  "
          f"|psi_m2|  ={float(torch.sqrt((psi_m2_t**2).mean())):.4e}")

    # ----- IC spectrum diagnostic ----- #
    # Print top-20 wavenumbers by enstrophy density Z(k) and energy density E(k).
    # For a band-limited IC (e.g. wavenumbers=[10,32]) this should show
    # essentially all the energy in that band and machine zero elsewhere.
    # If you see broad spread already at t=0, EITHER your IC is broad-band
    # OR you've already had nontrivial evolution before t* (which is the case
    # here since t* sits well into the developed-turbulence regime of the
    # parent FR run).
    om0_np = omega_0_t[0].cpu().numpy().astype(np.float64)
    kc_ic, Zk_ic = enstrophy_spectrum(om0_np, Lx, Ly)
    _,     Ek_ic = energy_spectrum(om0_np, Lx, Ly)
    dk_ic = kc_ic[1] - kc_ic[0]
    total_Z = float(np.sum(Zk_ic) * dk_ic)
    total_E = float(np.sum(Ek_ic) * dk_ic)
    print(f"[rollout] IC spectrum check (omega_0):")
    print(f"           total enstrophy = sum Z(k) dk = {total_Z:.4e}")
    print(f"           total energy    = sum E(k) dk = {total_E:.4e}")
    print(f"           direct: 0.5<omega^2> = {0.5*float(np.mean(om0_np**2)):.4e} "
          f"(should equal total enstrophy)")
    order = np.argsort(Zk_ic)[::-1]
    print(f"           top-10 Z(k) bins:")
    for i in order[:10]:
        print(f"             k={kc_ic[i]:7.2f}  Z(k)={Zk_ic[i]:.3e}  E(k)={Ek_ic[i]:.3e}")

    # ----- Snapshot steps ----- #
    frac_list = [float(s) for s in args.snapshot_fracs.split(',')]
    snapshot_steps = sorted(set(int(round(f * args.n_steps)) for f in frac_list))
    print(f"[rollout] snapshot steps: {snapshot_steps}")

    # ----- One-shot closure diagnostic at the IC ----- #
    # Run the NN forward on (omega_0, omega_m1, omega_m2, psi_0, psi_m1, psi_m2)
    # exactly as it will be called during the rollout, and compare against
    # f_NN_target stored in the npz.  This isolates whether the closure
    # decomposition is healthy *before* we run the long rollout.
    print(f"\n[rollout] === closure decomposition diagnostic at IC ===")
    if 'f_NN_target' in rec.files and 'e_total' in rec.files and \
       'e_anal_incr' in rec.files and 'e_NN_incr' in rec.files:
        from qg.solver.opt.basis import to_spectral, to_physical
        # Truth (from the builder):
        f_NN_target_np = rec['f_NN_target'].astype(np.float64)
        e_total_np     = rec['e_total'].astype(np.float64)
        e_anal_np      = rec['e_anal_incr'].astype(np.float64)
        e_NN_np        = rec['e_NN_incr'].astype(np.float64)
        if f_NN_target_np.ndim == 3:
            f_NN_target_np = f_NN_target_np[0]
        if e_total_np.ndim == 3:
            e_total_np = e_total_np[0]
        if e_anal_np.ndim == 3:
            e_anal_np = e_anal_np[0]
        if e_NN_np.ndim == 3:
            e_NN_np = e_NN_np[0]

        # Run the NN on the IC inputs (normalize inputs to match training space)
        x_ic = assemble_inputs(input_fields, omega_init_stack, psi_init_stack,
                                derivative, L_hat, F_phys, dtype, device)
        x_ic_norm = normalize_inputs(x_ic)
        with torch.no_grad():
            yhat_ic = model(x_ic_norm.to(dtype=model_dtype))
        yhat_ic = yhat_ic.to(dtype=dtype)
        f_NN_pred_t  = denormalize_target(yhat_ic)[0, 0]
        f_NN_pred_np = f_NN_pred_t.cpu().numpy()

        # And the analytical bracket at the IC
        E_anal_ic = E_analytical_phys(omega_init_stack[0], derivative,
                                        L_hat, F_phys)[0].cpu().numpy()
        K_train = training_K
        Delta_T_train = training_Delta_T
        coef_train = (Delta_T_train ** 3) * (1.0 - 1.0 / K_train ** 2)
        e_anal_pred_np = -coef_train * E_anal_ic
        e_NN_pred_np   = -coef_train * f_NN_pred_np

        def _l2(a):
            return float(np.sqrt(np.mean(a ** 2)))

        def _cos(a, b):
            num = float(np.sum(a * b))
            den = float(np.sqrt(np.sum(a ** 2)) * np.sqrt(np.sum(b ** 2)))
            return num / max(den, 1e-30)

        # f_NN_target check
        l2_tgt  = _l2(f_NN_target_np)
        l2_pred = _l2(f_NN_pred_np)
        l2_res  = _l2(f_NN_pred_np - f_NN_target_np)
        cos_fNN = _cos(f_NN_pred_np, f_NN_target_np)
        rel_res_fNN = l2_res / max(l2_tgt, 1e-30)
        if forward_resampled:
            print(f"  *** NPZ-vs-NN comparisons below are NOT VALID for forward-resampled IC. ***")
            print(f"  *** The npz's f_NN_target is at the npz's omega_0, not our new omega_0. ***")
            print(f"  *** Numbers printed are kept for magnitude-sanity but not accuracy.     ***")

        # Sign sanity: are pred and target the same sign (in spatial mean)?
        mean_tgt  = float(np.mean(f_NN_target_np))
        mean_pred = float(np.mean(f_NN_pred_np))
        std_tgt   = float(np.std(f_NN_target_np))
        std_pred  = float(np.std(f_NN_pred_np))
        print(f"  f_NN_target (from npz):  |f_NN_target|_2 = {l2_tgt:.4e}  "
              f"mean={mean_tgt:+.4e}  std={std_tgt:.4e}")
        print(f"  f_NN_pred   (from NN) :  |f_NN_pred|_2   = {l2_pred:.4e}  "
              f"mean={mean_pred:+.4e}  std={std_pred:.4e}")
        print(f"  |f_NN_pred - f_NN_target|_2              = {l2_res:.4e}")
        print(f"  rel-L2 residual on f_NN                  = {rel_res_fNN:.4f}  "
              f"(should match val rel-L2 from training, ~0.19)")
        print(f"  cos(f_NN_pred, f_NN_target)              = {cos_fNN:.6f}  "
              f"(1.0 = perfect direction; but dominated by spatial mean!)")

        # KEY DIAGNOSTIC: split into mean + deviation.
        # f_NN_target has mean ~0.94 and std ~0.29.  The spatial mean is ~3x
        # bigger than the spatial fluctuation.  If the NN merely predicts
        # the mean as a constant, val rel-L2 is ~0.30 (still small-looking)
        # and cos is ~1.0 -- but the closure helps essentially zero because
        # a constant shift can't fix spatial structure of e_total.
        dev_tgt  = f_NN_target_np - mean_tgt
        dev_pred = f_NN_pred_np   - mean_pred
        cos_dev  = _cos(dev_pred, dev_tgt)
        l2_dev_tgt = _l2(dev_tgt)
        l2_dev_pred = _l2(dev_pred)
        l2_dev_res = _l2(dev_pred - dev_tgt)
        rel_dev    = l2_dev_res / max(l2_dev_tgt, 1e-30)
        print(f"  DEVIATION-only (= f_NN_* - spatial_mean):")
        print(f"    |dev_target|_2 = {l2_dev_tgt:.4e}  "
              f"|dev_pred|_2 = {l2_dev_pred:.4e}  "
              f"|dev_pred - dev_target|_2 = {l2_dev_res:.4e}")
        print(f"    rel-L2 on deviations  = {rel_dev:.4f}")
        print(f"    cos on deviations     = {cos_dev:.6f}  "
              f"(THIS is what actually matters for closure recovery)")
        print(f"    mean / total enstrophy frac: target={(mean_tgt*np.sqrt(len(f_NN_target_np.flatten())))**2/max(l2_tgt**2*len(f_NN_target_np.flatten()),1e-30):.3f}")
        print()

        # Increment-level checks
        # NOTE: the npz e_anal_incr/e_NN_incr/e_total use coef_train.  Our
        # rollout uses (Delta_T_override)^3 / ... -- but for sample 100 with
        # NO override, they should match exactly.
        l2_etot  = _l2(e_total_np)
        l2_eanal = _l2(e_anal_np)
        l2_eNN   = _l2(e_NN_np)
        cos_eanal_npz = _cos(e_anal_pred_np, e_anal_np)
        cos_eNN_npz   = _cos(e_NN_pred_np,   e_NN_np)
        print(f"  e_total  (from npz)  |e_total|_2    = {l2_etot:.4e}")
        print(f"  e_anal   (from npz)  |e_anal|_2     = {l2_eanal:.4e}  "
              f"(frac of e_total: {l2_eanal/max(l2_etot,1e-30):.4f})")
        print(f"  e_NN     (from npz)  |e_NN|_2       = {l2_eNN:.4e}  "
              f"(frac of e_total: {l2_eNN/max(l2_etot,1e-30):.4f})")
        print(f"  e_anal   (recomputed): |.|_2        = {_l2(e_anal_pred_np):.4e}  "
              f"cos vs npz = {cos_eanal_npz:.6f}")
        print(f"  e_NN     (NN predict): |.|_2        = {_l2(e_NN_pred_np):.4e}  "
              f"cos vs npz = {cos_eNN_npz:.6f}")
        print()

        # Decomposition predictions for closure-vs-bare residual at step 1.
        # CRITICAL CAVEAT: the npz's `e_total = omega_K_fine - omega_1_coarse`
        # uses the BUILDER's truth definition (omega_K_fine generated by K
        # fine AB2CN2 steps seeded with the COARSE-buffer stencil (omega_m1,
        # omega_0) -- which differs from omega_0 by Delta_T, not h_fine).
        # The ROLLOUT's truth uses the PROPER fine stencil: ultrafine RK4
        # backward to bootstrap qh_minus at h_fine spacing, then a continuous
        # AB2CN2-at-h_fine run.  These two truth definitions differ by an
        # O(K*h_fine^2 * Ndot) "AB2-stencil contamination" term that is the
        # same order of magnitude as e_total itself.
        #
        # So we predict the closure recovery against BOTH references:
        # (a) builder's npz e_total  (the "training-targeted" reference)
        # (b) rollout's actual one-step bare-vs-truth  (the "deployment-relevant" reference)
        # The observed rollout improvement at step 1 should match (b), not (a).

        # (a) NPZ-reference prediction (informational)
        if not forward_resampled:
            residual_npz = e_total_np - e_anal_pred_np - e_NN_pred_np
            l2_residual_npz = _l2(residual_npz)
            improvement_npz = 1 - l2_residual_npz / max(l2_etot, 1e-30)
            print(f"  predicted closure recovery (vs NPZ truth, contaminated reference):")
            print(f"    |e_total_npz - e_anal_pred - e_NN_pred|_2 = {l2_residual_npz:.4e}")
            print(f"    1 - |residual|/|e_total_npz| = {improvement_npz:.4f}")
            print(f"    (this is what the closure was *trained* against;")
            print(f"     the npz's e_total is contaminated by AB2-stencil mismatch")
            print(f"     in the builder's fine-reference; not what we compare to)")
        else:
            print(f"  [skip NPZ-reference prediction: forward-resampled IC means")
            print(f"   the npz's e_total/e_anal/e_NN were for a different omega_0")
            print(f"   (the one at npz seed_t + 3*Delta_T_training), not this one]")

        # (b) ROLLOUT-reference prediction: actually run one bare + one
        #     fine-truth step and compare.  This is the apples-to-apples
        #     reference for the closure's deployment value.
        print(f"  predicted closure recovery (vs ROLLOUT truth, proper h_fine stencil):")
        try:
            # One bare step at Delta_T (uses training Delta_T since we haven't
            # overridden in this diagnostic path)
            qh_b_curr_t  = to_spectral(omega_init_stack[0])
            qh_b_minus_t = to_spectral(omega_init_stack[1])
            qh_b_new_t = ab2cn2_step_spectral(qh_b_curr_t, qh_b_minus_t, Delta_T,
                                                derivative, L_hat, F_phys)
            om_b_step1 = to_physical(qh_b_new_t)

            # One block of K fine-truth steps with proper stencil
            om_t_curr = omega_init_stack[0].clone()
            om_t_minus_fine = rk4_step(om_t_curr, -h_fine, derivative, L_hat, F_phys)
            qh_t_curr_d  = to_spectral(om_t_curr)
            qh_t_minus_d = to_spectral(om_t_minus_fine)
            for _ in range(K):
                qh_t_next = ab2cn2_step_spectral(qh_t_curr_d, qh_t_minus_d, h_fine,
                                                   derivative, L_hat, F_phys)
                qh_t_minus_d, qh_t_curr_d = qh_t_curr_d, qh_t_next
            om_t_step1 = to_physical(qh_t_curr_d)

            # Build closure correction at the IC
            # (already computed above as e_anal_pred_np + e_NN_pred_np in numpy)
            e_anal_pred_t = torch.from_numpy(e_anal_pred_np[None]).to(
                dtype=dtype, device=device)
            e_NN_pred_t   = torch.from_numpy(e_NN_pred_np[None]).to(
                dtype=dtype, device=device)
            om_c_step1 = om_b_step1 + e_anal_pred_t + e_NN_pred_t

            db_rollout = (om_b_step1 - om_t_step1)[0].cpu().numpy()
            dc_rollout = (om_c_step1 - om_t_step1)[0].cpu().numpy()
            l2_db = _l2(db_rollout)
            l2_dc = _l2(dc_rollout)
            improvement_rollout = 1 - l2_dc / max(l2_db, 1e-30)
            print(f"    |om_bare_step1 - om_truth_step1|_2     = {l2_db:.4e}")
            print(f"    |om_closure_step1 - om_truth_step1|_2  = {l2_dc:.4e}")
            print(f"    1 - |closure_err|/|bare_err| = {improvement_rollout:.4f}")
            print(f"    rel_clos / rel_bare           = {l2_dc/max(l2_db,1e-30):.4f}")
            print(f"    (this should match the per-step rollout output to <1%)")
        except NameError:
            print(f"    [skip: to_spectral_t / to_physical_t not in scope here]")
        except Exception as _e:
            print(f"    [skip: {_e}]")
    else:
        print(f"  [skip] missing some of f_NN_target/e_total/e_anal_incr/e_NN_incr "
              f"in npz; can't run diagnostic")
    print("=" * 70)

    # ----- Run the three rollouts, keeping every step's omega ----- #
    # Memory cost: (n_steps+1) * Nx * Ny * 8 bytes per trajectory.
    # For 256^2 over 500 steps that's 263 MB per trajectory, 790 MB total --
    # fits in RAM/GPU.  We need the full per-step fields to compute the
    # |omega - omega_truth| error curves, so we hold them in memory.
    # ---- Snapshot stride: keep full fields only at S-step intervals ---- #
    # Even at the largest n_steps we want O(snapshots) full fields kept, not
    # O(n_steps).  Per-step scalars (L^2 error, rms, enstrophy) are kept at
    # every step -- they're cheap (8 bytes each).
    log_stride = max(1, args.n_steps // 500)   # cap retained frames at ~500
    n_frames = (args.n_steps // log_stride) + 1
    print(f"[rollout] snapshot/log stride: keep every {log_stride}-th step "
          f"({n_frames} frames retained per trajectory)")

    # Snapshot steps (for the field panels) are forced to coincide with stride
    # boundaries so we have them in the frame buffer.
    frac_list = [float(s) for s in args.snapshot_fracs.split(',')]
    raw_snap = [int(round(f * args.n_steps)) for f in frac_list]
    snap_aligned = sorted({(s // log_stride) * log_stride for s in raw_snap})
    snapshot_steps = snap_aligned
    print(f"[rollout] snapshot steps (aligned to stride): {snapshot_steps}")
    snap_set = set(snapshot_steps)

    def triple_rollout():
        """
        Run truth + bare + closure in lockstep, one outer iteration per
        coarse step.  At every step we accumulate per-step scalars
        (rel-L^2 vs truth, |omega|_2, enstrophy).  We retain full omega
        fields ONLY at log_stride boundaries (and always at step 0 and
        the snapshot_steps).  Memory drops by a factor of log_stride.
        """
        from qg.solver.opt.basis import to_spectral, to_physical

        # --- Truth buffers (fine spacing h_fine) --- #
        om_t = omega_init_stack[0].clone()
        om_t_minus = rk4_step(om_t, -h_fine, derivative, L_hat, F_phys)
        qh_t_curr  = to_spectral(om_t)
        qh_t_minus = to_spectral(om_t_minus)

        # --- Bare buffer (coarse spacing Delta_T) --- #
        bare_omega = [w.clone() for w in omega_init_stack]

        # --- Closure buffers (coarse spacing Delta_T) --- #
        clos_omega = [w.clone() for w in omega_init_stack]
        clos_psi   = [w.clone() for w in psi_init_stack]

        K_factor = 1.0 - 1.0 / (K ** 2)
        coef = (Delta_T ** 3) * K_factor

        n = args.n_steps
        # Per-step scalar arrays
        rel_bare = np.zeros(n + 1)
        abs_bare = np.zeros(n + 1)
        rel_clos = np.zeros(n + 1)
        abs_clos = np.zeros(n + 1)
        fine_rms = np.zeros(n + 1)
        bare_rms = np.zeros(n + 1)
        clos_rms = np.zeros(n + 1)
        fine_Z   = np.zeros(n + 1)
        bare_Z   = np.zeros(n + 1)
        clos_Z   = np.zeros(n + 1)

        # Retained frames (small): step -> (Ny, Nx) np float32
        fine_frames = {}
        bare_frames = {}
        clos_frames = {}

        def _stash(step, om_t_np, om_b_np, om_c_np):
            fine_frames[step] = om_t_np.astype(np.float32).copy()
            bare_frames[step] = om_b_np.astype(np.float32).copy()
            clos_frames[step] = om_c_np.astype(np.float32).copy()

        # Step 0: all three are identical to omega_0
        om_t_np_0 = om_t[0].cpu().numpy()
        rel_bare[0] = 0.0; abs_bare[0] = 0.0
        rel_clos[0] = 0.0; abs_clos[0] = 0.0
        rms_t0 = float(np.sqrt(np.mean(om_t_np_0 ** 2)))
        fine_rms[0] = bare_rms[0] = clos_rms[0] = rms_t0
        Z_t0 = 0.5 * float(np.mean(om_t_np_0 ** 2))
        fine_Z[0] = bare_Z[0] = clos_Z[0] = Z_t0
        _stash(0, om_t_np_0, om_t_np_0, om_t_np_0)

        t0_wall = time.time()
        for step in range(1, n + 1):
            # --- Truth: K AB2CN2 steps at h_fine --- #
            for _ in range(K):
                qh_t_next = ab2cn2_step_spectral(qh_t_curr, qh_t_minus, h_fine,
                                                  derivative, L_hat, F_phys)
                qh_t_minus, qh_t_curr = qh_t_curr, qh_t_next
            om_t = to_physical(qh_t_curr)

            # --- Bare: one AB2CN2 step at Delta_T --- #
            qh_b_curr  = to_spectral(bare_omega[0])
            qh_b_minus = to_spectral(bare_omega[1])
            qh_b_new = ab2cn2_step_spectral(qh_b_curr, qh_b_minus, Delta_T,
                                              derivative, L_hat, F_phys)
            om_b = to_physical(qh_b_new)
            bare_omega = [om_b, bare_omega[0], bare_omega[1]]

            # --- Closure: AB2CN2 + e_anal + e_NN --- #
            qh_c_curr  = to_spectral(clos_omega[0])
            qh_c_minus = to_spectral(clos_omega[1])
            qh_c_bare = ab2cn2_step_spectral(qh_c_curr, qh_c_minus, Delta_T,
                                               derivative, L_hat, F_phys)
            om_c_bare = to_physical(qh_c_bare)
            E_anal = E_analytical_phys(clos_omega[0], derivative, L_hat, F_phys)
            e_anal_inc = -coef * E_anal
            x = assemble_inputs(input_fields, clos_omega, clos_psi,
                                 derivative, L_hat, F_phys, dtype, device)
            x_norm = normalize_inputs(x)
            with torch.no_grad():
                yhat = model(x_norm.to(dtype=model_dtype))
            yhat = yhat.to(dtype=dtype)
            f_NN_pred = denormalize_target(yhat)[0, 0][None]   # (1, Ny, Nx)
            e_NN_inc = -coef * f_NN_pred
            om_c = om_c_bare + e_anal_inc + e_NN_inc
            clos_omega = [om_c, clos_omega[0], clos_omega[1]]
            clos_psi   = [psi_from_omega(om_c, derivative),
                          clos_psi[0], clos_psi[1]]

            # --- Per-step scalars (compute on GPU, cast to host scalars) --- #
            om_t_np = om_t[0].cpu().numpy()
            om_b_np = om_b[0].cpu().numpy()
            om_c_np = om_c[0].cpu().numpy()
            t_norm = float(np.sqrt(np.mean(om_t_np ** 2)))
            fine_rms[step] = t_norm
            bare_rms[step] = float(np.sqrt(np.mean(om_b_np ** 2)))
            clos_rms[step] = float(np.sqrt(np.mean(om_c_np ** 2)))
            fine_Z[step]   = 0.5 * float(np.mean(om_t_np ** 2))
            bare_Z[step]   = 0.5 * float(np.mean(om_b_np ** 2))
            clos_Z[step]   = 0.5 * float(np.mean(om_c_np ** 2))
            db = om_b_np - om_t_np
            dc = om_c_np - om_t_np
            abs_bare[step] = float(np.sqrt(np.mean(db ** 2)))
            abs_clos[step] = float(np.sqrt(np.mean(dc ** 2)))
            den = max(t_norm, 1e-30)
            rel_bare[step] = abs_bare[step] / den
            rel_clos[step] = abs_clos[step] / den

            # Retain full fields at stride boundaries, snapshot steps, or the final step
            if (step % log_stride == 0) or (step in snap_set) or (step == n):
                _stash(step, om_t_np, om_b_np, om_c_np)

            if step % max(1, n // 20) == 0:
                el = time.time() - t0_wall
                eta = el * (n - step) / max(step, 1)
                print(f"      step {step:6d}/{n}  rel_bare={rel_bare[step]:.3e}  "
                      f"rel_clos={rel_clos[step]:.3e}  "
                      f"rms_t={t_norm:.3e}  elapsed={el:.1f}s  eta={eta:.1f}s")

        return dict(
            rel_bare=rel_bare, abs_bare=abs_bare,
            rel_clos=rel_clos, abs_clos=abs_clos,
            fine_rms=fine_rms, bare_rms=bare_rms, clos_rms=clos_rms,
            fine_Z=fine_Z,     bare_Z=bare_Z,     clos_Z=clos_Z,
            fine_frames=fine_frames, bare_frames=bare_frames, clos_frames=clos_frames,
        )

    print("\n[rollout] === triple rollout (synchronized truth + bare + closure) ===")
    out = triple_rollout()
    rel_bare, abs_bare = out['rel_bare'], out['abs_bare']
    rel_clos, abs_clos = out['rel_clos'], out['abs_clos']
    fine_rms_full = out['fine_rms']; bare_rms_full = out['bare_rms']; clos_rms_full = out['clos_rms']
    fine_Z_full   = out['fine_Z'];   bare_Z_full   = out['bare_Z'];   clos_Z_full   = out['clos_Z']
    fine_frames   = out['fine_frames']
    bare_frames   = out['bare_frames']
    clos_frames   = out['clos_frames']

    # Build sparse "hist" arrays that include exactly the retained frames,
    # plus a parallel index array so render_figure can look them up.
    retained_steps = sorted(fine_frames.keys())
    fine_hist = np.stack([fine_frames[s] for s in retained_steps], axis=0)
    bare_hist = np.stack([bare_frames[s] for s in retained_steps], axis=0)
    clos_hist = np.stack([clos_frames[s] for s in retained_steps], axis=0)
    retained_steps_arr = np.asarray(retained_steps, dtype=np.int64)
    # Quick sanity prints
    print(f"[rollout] retained {len(retained_steps)} field frames; "
          f"streamed per-step scalars for {args.n_steps + 1} steps")
    print(f"[rollout] final rel-L2:  bare={rel_bare[-1]:.4e}  "
          f"closure={rel_clos[-1]:.4e}  "
          f"improvement={rel_bare[-1]/max(rel_clos[-1], 1e-30):.2f}x")

    # ----- Save raw arrays ----- #
    npz_out = out_dir / f'rollout_multistep_{ic_tag}.npz'
    np.savez(npz_out,
             fine_hist=fine_hist,                       # already float32
             bare_hist=bare_hist,
             clos_hist=clos_hist,
             retained_steps=retained_steps_arr,
             rel_bare=rel_bare, abs_bare=abs_bare,
             rel_clos=rel_clos, abs_clos=abs_clos,
             snapshot_steps=np.asarray(snapshot_steps, dtype=np.int64),
             fine_rms=fine_rms_full, bare_rms=bare_rms_full, clos_rms=clos_rms_full,
             fine_Z=fine_Z_full,     bare_Z=bare_Z_full,     clos_Z=clos_Z_full,
             Delta_T=Delta_T, K=K, h_fine=h_fine,
             Lx=Lx, Ly=Ly, nu=nu, mu=mu, beta=beta,
             training_Delta_T=training_Delta_T,
             training_K=training_K)
    print(f"[rollout] wrote arrays: {npz_out}")

    # ----- Render figure ----- #
    fig_path = out_dir / f'rollout_multistep_{ic_tag}.png'
    render_figure(fine_hist, bare_hist, clos_hist, retained_steps_arr,
                  rel_bare, rel_clos, abs_bare, abs_clos,
                  fine_rms_full, bare_rms_full, clos_rms_full,
                  fine_Z_full, bare_Z_full, clos_Z_full,
                  snapshot_steps, Delta_T, K, Lx, Ly, model_name,
                  fig_path)

    # ----- Save metadata ----- #
    json_out = out_dir / f'rollout_multistep_{ic_tag}.json'
    with open(json_out, 'w') as fjson:
        json.dump(dict(
            run_dir=str(args.run_dir),
            root_dir=str(args.root_dir),
            n_steps=int(args.n_steps),
            ic_index=int(args.ic_index),
            split=args.split,
            manifest_idx=int(manifest_idx),
            input_fields=list(input_fields),
            model_name=model_name,
            Delta_T=Delta_T, K=K, h_fine=h_fine,
            Nx=Nx, Ny=Ny, Lx=Lx, Ly=Ly, nu=nu, mu=mu, beta=beta,
            snapshot_steps=snapshot_steps,
            final_rel_err_bare=float(rel_bare[-1]),
            final_rel_err_closure=float(rel_clos[-1]),
            error_reduction_factor=float(rel_bare[-1] / max(rel_clos[-1], 1e-30)),
        ), fjson, indent=2)
    print(f"[rollout] wrote metadata: {json_out}")
    print(f"[rollout] DONE.")


# --------------------------------------------------------------------------- #
# Figure                                                                      #
# --------------------------------------------------------------------------- #

def render_figure(fine_hist, bare_hist, clos_hist, retained_steps,
                   rel_bare, rel_clos, abs_bare, abs_clos,
                   fine_rms, bare_rms, clos_rms,
                   fine_Z, bare_Z, clos_Z,
                   snapshot_steps, Delta_T, K, Lx, Ly, model_name,
                   out_path):
    """Multi-row figure (one row per snapshot step + 3 rows of diagnostics).

    *_hist are SPARSE -- shape (n_retained, Ny, Nx), one frame per coarse
    step listed in `retained_steps`.  Per-step scalar arrays (rel_*, abs_*,
    *_rms, *_Z) are DENSE -- shape (n_steps + 1,), one value per coarse step.
    """
    # Build a step -> sparse-index map so snapshot_steps work in any order
    step_to_idx = {int(s): i for i, s in enumerate(retained_steps)}

    def get_frames(step):
        i = step_to_idx[int(step)]
        return fine_hist[i], bare_hist[i], clos_hist[i]

    n_snaps = len(snapshot_steps)
    n_cols  = 5
    n_bottom = 4   # error curves / rms+Z / spectra@t=0 / spectra@t=final
    fig_h = 3.2 * n_snaps + n_bottom * 3.0
    fig = plt.figure(figsize=(n_cols * 3.0, fig_h))
    outer = gridspec.GridSpec(n_snaps + n_bottom, n_cols, figure=fig,
                               hspace=0.55, wspace=0.30)

    # ---- Row block 1: snapshot rows ---- #
    for row_i, step in enumerate(snapshot_steps):
        omega_truth, omega_bare, omega_clos = get_frames(step)
        v = float(np.max(np.abs(np.stack([omega_truth, omega_bare, omega_clos]))))
        if v == 0: v = 1.0
        diff_bare = omega_bare - omega_truth
        diff_clos = omega_clos - omega_truth
        v_diff = float(np.max(np.abs(np.concatenate([diff_bare.ravel(),
                                                      diff_clos.ravel()]))))
        if v_diff == 0: v_diff = 1.0

        t_phys = step * Delta_T

        ax = fig.add_subplot(outer[row_i, 0])
        ax.imshow(omega_truth, cmap='RdBu_r', vmin=-v, vmax=v,
                  origin='lower', aspect='equal', interpolation='gaussian')
        ax.set_title(rf'truth  $t = {t_phys:.3f}$' '\n' rf'(step {step})',
                     fontsize=10)
        ax.set_xticks([]); ax.set_yticks([])
        ax.set_ylabel(rf'step {step}', fontsize=10)

        ax = fig.add_subplot(outer[row_i, 1])
        ax.imshow(omega_bare, cmap='RdBu_r', vmin=-v, vmax=v,
                  origin='lower', aspect='equal', interpolation='gaussian')
        ax.set_title('bare coarse', fontsize=10)
        ax.set_xticks([]); ax.set_yticks([])

        ax = fig.add_subplot(outer[row_i, 2])
        ax.imshow(omega_clos, cmap='RdBu_r', vmin=-v, vmax=v,
                  origin='lower', aspect='equal', interpolation='gaussian')
        ax.set_title('coarse + closure', fontsize=10)
        ax.set_xticks([]); ax.set_yticks([])

        ax = fig.add_subplot(outer[row_i, 3])
        ax.imshow(diff_bare, cmap='seismic', vmin=-v_diff, vmax=v_diff,
                  origin='lower', aspect='equal', interpolation='gaussian')
        rel_b = np.sqrt(np.mean(diff_bare**2)) / np.sqrt(np.mean(omega_truth**2)+1e-30)
        ax.set_title(rf'bare $-$ truth' '\n' rf'rel $L^2={rel_b:.3f}$',
                     fontsize=10)
        ax.set_xticks([]); ax.set_yticks([])

        ax = fig.add_subplot(outer[row_i, 4])
        ax.imshow(diff_clos, cmap='seismic', vmin=-v_diff, vmax=v_diff,
                  origin='lower', aspect='equal', interpolation='gaussian')
        rel_c = np.sqrt(np.mean(diff_clos**2)) / np.sqrt(np.mean(omega_truth**2)+1e-30)
        ax.set_title(rf'closure $-$ truth' '\n' rf'rel $L^2={rel_c:.3f}$',
                     fontsize=10)
        ax.set_xticks([]); ax.set_yticks([])

    # ---- Row block 2: error-vs-time curves ---- #
    n_steps = len(rel_bare) - 1
    t_axis = np.arange(0, n_steps + 1) * Delta_T

    ax = fig.add_subplot(outer[n_snaps, 0:2])
    ax.semilogy(t_axis, rel_bare + 1e-30, 'C0-', lw=1.6, label='bare coarse')
    ax.semilogy(t_axis, rel_clos + 1e-30, 'C2-', lw=1.6, label='coarse + closure')
    ax.set_xlabel(r'physical time  $t = m\Delta T$', fontsize=10)
    ax.set_ylabel(r'rel. $L^2$ error vs truth', fontsize=10)
    ax.set_title('relative error growth', fontsize=11)
    ax.grid(True, which='both', alpha=0.3)
    ax.legend(fontsize=9, loc='best')

    ax = fig.add_subplot(outer[n_snaps, 2:4])
    ax.semilogy(t_axis, abs_bare + 1e-30, 'C0-', lw=1.6, label='bare coarse')
    ax.semilogy(t_axis, abs_clos + 1e-30, 'C2-', lw=1.6, label='coarse + closure')
    ax.set_xlabel(r'physical time  $t = m\Delta T$', fontsize=10)
    # Colleague's convention (convergence_t10_plot_titled.py):
    #   err = sqrt( mean( (omega_dt - omega_truth)^2 ) )
    # i.e. absolute RMS of the difference field.  Same formula as line 750-751
    # above (np.sqrt(np.mean(db ** 2))).
    ax.set_ylabel(r'$\|\omega(t) - \omega_{\Delta t}(t)\|$', fontsize=10)
    ax.set_title('absolute RMS error growth (colleague conv.)', fontsize=11)
    ax.grid(True, which='both', alpha=0.3)
    ax.legend(fontsize=9, loc='best')

    ax = fig.add_subplot(outer[n_snaps, 4])
    improvement = rel_bare / np.maximum(rel_clos, 1e-30)
    ax.semilogy(t_axis, improvement, 'k-', lw=1.6)
    ax.axhline(1.0, color='gray', ls='--', lw=1)
    ax.set_xlabel(r'$t$', fontsize=10)
    ax.set_ylabel(r'rel-error ratio (bare / closure)', fontsize=9)
    ax.set_title('improvement factor', fontsize=10)
    ax.grid(True, which='both', alpha=0.3)

    # ---- Row block 3: rms-omega and enstrophy trajectories ---- #
    ax = fig.add_subplot(outer[n_snaps + 1, 0:2])
    ax.plot(t_axis, fine_rms, 'k-',  lw=1.6, label='truth')
    ax.plot(t_axis, bare_rms, 'C0-', lw=1.2, label='bare coarse')
    ax.plot(t_axis, clos_rms, 'C2-', lw=1.2, label='coarse + closure')
    ax.set_xlabel(r'$t$', fontsize=10)
    ax.set_ylabel(r'$\|\omega(t)\|_2$', fontsize=10)
    ax.set_title('rms vorticity', fontsize=11)
    ax.grid(True, alpha=0.3)
    ax.legend(fontsize=9, loc='best')

    ax = fig.add_subplot(outer[n_snaps + 1, 2:4])
    ax.plot(t_axis, fine_Z, 'k-',  lw=1.6, label='truth')
    ax.plot(t_axis, bare_Z, 'C0-', lw=1.2, label='bare coarse')
    ax.plot(t_axis, clos_Z, 'C2-', lw=1.2, label='coarse + closure')
    ax.set_xlabel(r'$t$', fontsize=10)
    ax.set_ylabel(r'$Z(t) = \frac{1}{2} \langle \omega^2 \rangle$', fontsize=10)
    ax.set_title('mean enstrophy', fontsize=11)
    ax.grid(True, alpha=0.3)
    ax.legend(fontsize=9, loc='best')

    ax = fig.add_subplot(outer[n_snaps + 1, 4])
    # |Z - Z_truth| / Z_truth -- relative enstrophy error
    rel_Z_bare = np.abs(bare_Z - fine_Z) / np.maximum(fine_Z, 1e-30)
    rel_Z_clos = np.abs(clos_Z - fine_Z) / np.maximum(fine_Z, 1e-30)
    ax.semilogy(t_axis, rel_Z_bare + 1e-30, 'C0-', lw=1.2, label='bare')
    ax.semilogy(t_axis, rel_Z_clos + 1e-30, 'C2-', lw=1.2, label='closure')
    ax.set_xlabel(r'$t$', fontsize=10)
    ax.set_ylabel(r'rel. $Z$ error', fontsize=9)
    ax.set_title('enstrophy drift', fontsize=10)
    ax.grid(True, which='both', alpha=0.3)
    ax.legend(fontsize=8, loc='best')

    # ---- Row block 4: spectra ----------------------------------------- #
    # Two rows: t=0 (IC) and t=final. Helps disambiguate "spectrum shape
    # is from the IC" vs "spectrum shape evolved" -- the question that comes
    # up immediately when the t=final spectrum doesn't show a clean cascade.
    omega_truth_0 = fine_hist[0]
    omega_bare_0  = bare_hist[0]
    omega_clos_0  = clos_hist[0]
    kc, E_truth_0 = energy_spectrum(omega_truth_0, Lx, Ly)
    _,  Z_truth_0_k = enstrophy_spectrum(omega_truth_0, Lx, Ly)
    # bare/closure are bit-identical to truth at t=0 by construction, but
    # plot them anyway as a sanity check
    _,  E_bare_0 = energy_spectrum(omega_bare_0, Lx, Ly)
    _,  E_clos_0 = energy_spectrum(omega_clos_0, Lx, Ly)
    _,  Z_bare_0_k = enstrophy_spectrum(omega_bare_0, Lx, Ly)
    _,  Z_clos_0_k = enstrophy_spectrum(omega_clos_0, Lx, Ly)

    omega_truth_f = fine_hist[-1]
    omega_bare_f  = bare_hist[-1]
    omega_clos_f  = clos_hist[-1]
    _,  E_truth_f = energy_spectrum(omega_truth_f, Lx, Ly)
    _,  E_bare_f  = energy_spectrum(omega_bare_f,  Lx, Ly)
    _,  E_clos_f  = energy_spectrum(omega_clos_f,  Lx, Ly)
    _,  Z_truth_f_k = enstrophy_spectrum(omega_truth_f, Lx, Ly)
    _,  Z_bare_f_k  = enstrophy_spectrum(omega_bare_f,  Lx, Ly)
    _,  Z_clos_f_k  = enstrophy_spectrum(omega_clos_f,  Lx, Ly)

    kk = kc[1:]

    def _slope_anchor(spectrum_arr, slope):
        """Anchor a reference slope to the spectrum peak; return (mask, anchor)."""
        if len(kk) <= 4 or spectrum_arr.max() <= 0:
            return np.zeros_like(kk, dtype=bool), 1.0
        k_peak = float(kk[int(np.argmax(spectrum_arr))])
        k_lo = max(k_peak,        kk[0])
        k_hi = min(k_peak * 10.0, kk[-1] * 0.8)
        mask = (kk >= k_lo) & (kk <= k_hi) & (spectrum_arr > 0)
        if not mask.any():
            return mask, 1.0
        anchor = spectrum_arr[mask][0] / (kk[mask][0] ** slope)
        return mask, anchor

    def _plot_spectrum(ax, kk, curves, title, ylabel, ref_slope, ref_label):
        # curves: list of (label, color, style, lw, data1d).
        for label, color, style, lw, data in curves:
            ax.loglog(kk, data[1:] + 1e-30, color=color, linestyle=style,
                      lw=lw, label=label)
        # Anchor on truth (assumed first curve)
        truth_data = curves[0][4][1:]
        mask, anchor = _slope_anchor(truth_data, ref_slope)
        if mask.any():
            ax.loglog(kk[mask], anchor * kk[mask] ** ref_slope,
                      'r--', lw=1, alpha=0.7, label=ref_label)
        ax.set_xlabel(r'$k$', fontsize=10)
        ax.set_ylabel(ylabel, fontsize=10)
        ax.set_title(title, fontsize=11)
        ax.grid(True, which='both', alpha=0.3)
        ax.legend(fontsize=8, loc='best')

    # --- Row n_snaps + 2: spectra at t = 0 (IC) --- #
    ax = fig.add_subplot(outer[n_snaps + 2, 0:2])
    _plot_spectrum(ax, kk, [
        ('truth IC', 'k', '-', 1.6, E_truth_0),
    ], rf'$E(k)$ at $t = 0$ (IC)',
       r'$E(k)$',  -5/3, r'$k^{-5/3}$ (ref)')

    ax = fig.add_subplot(outer[n_snaps + 2, 2:4])
    _plot_spectrum(ax, kk, [
        ('truth IC', 'k', '-', 1.6, Z_truth_0_k),
    ], rf'$Z(k)$ at $t = 0$ (IC)',
       r'$Z(k)$',  -3, r'$k^{-3}$ (ref)')

    # --- Row n_snaps + 3: spectra at t = final --- #
    t_final = n_steps * Delta_T
    ax = fig.add_subplot(outer[n_snaps + 3, 0:2])
    _plot_spectrum(ax, kk, [
        ('truth',   'k',  '-', 1.6, E_truth_f),
        ('bare',    'C0', '-', 1.2, E_bare_f),
        ('closure', 'C2', '-', 1.2, E_clos_f),
    ], rf'$E(k)$ at $t = {t_final:.3f}$',
       r'$E(k)$',  -5/3, r'$k^{-5/3}$ (ref)')

    ax = fig.add_subplot(outer[n_snaps + 3, 2:4])
    _plot_spectrum(ax, kk, [
        ('truth',   'k',  '-', 1.6, Z_truth_f_k),
        ('bare',    'C0', '-', 1.2, Z_bare_f_k),
        ('closure', 'C2', '-', 1.2, Z_clos_f_k),
    ], rf'$Z(k)$ at $t = {t_final:.3f}$',
       r'$Z(k)$',  -3, r'$k^{-3}$ (ref)')

    # ---- Title ---- #
    fig.suptitle(rf'Multi-step rollout: truth (fine, $K={K}$) vs bare coarse '
                 rf'($\Delta T = {Delta_T:g}$) vs coarse $+$ closure '
                 rf'({model_name})  --  {n_steps} coarse steps',
                 fontsize=13, y=0.998)
    fig.savefig(out_path, dpi=120, bbox_inches='tight')
    print(f"[rollout] wrote figure: {out_path}")


if __name__ == '__main__':
    main()